- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - name: Save Student SSH password as user.info
      agnosticd_user_info:
        data:
          student_ssh_password: >-
            {{ student_password | default(hostvars[groups.bastions.0].student_password) }}
          student_ssh_command: >-
            ssh {{ student_user }}@bastion.{{ subdomain_base }}
    - debug:
        msg: "Post-Software checks completed successfully"

- name: Sending Console URL for Azure and Documentation
  debug:
    msg: "{{ item }}"
  with_items:
    - "user.info: Bastion public hostname is bastion.{{ subdomain_base }}"
    - "user.info: ssh command is ssh {{ student_user }}@bastion.{{ subdomain_base }}"
    - "user.info: ssh password is {{ student_password | default(hostvars[groups.bastions.0].student_password) }}"